// <auto-generated />
using System;
using FinalAppTemplate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalAppTemplate.Migrations
{
    [DbContext(typeof(FinalAppTemplateDbContext))]
    partial class FinalAppTemplateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalAppTemplate.Models.Recommendation", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("SongId")
                        .HasColumnType("int")
                        .HasColumnName("song_id");

                    b.Property<DateTime?>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("score");

                    b.HasKey("UserId", "SongId")
                        .HasName("pk_recommendation");

                    b.HasIndex("SongId");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("FinalAppTemplate.Models.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("session_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("SessionId")
                        .HasName("PK__Sessions__69B13FDC7CDBD6DB");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Token" }, "UQ__Sessions__CA90DA7A01109920")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("FinalAppTemplate.Models.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("song_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SongId"));

                    b.Property<string>("Album")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("album");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("artist");

                    b.Property<string>("SpotifyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("spotify_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("SongId")
                        .HasName("PK__Songs__A535AE1CCE8D58AD");

                    b.HasIndex(new[] { "SpotifyId" }, "UQ__Songs__C253CFF10D62E3EF")
                        .IsUnique();

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("FinalAppTemplate.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_verified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("verification_token");

                    b.HasKey("UserId")
                        .HasName("PK__Users__B9BE370F0AD01AAF");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__AB6E616455510AF1")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ__Users__F3DBC57274E78E26")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinalAppTemplate.Models.UserSongFavorite", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("SongId")
                        .HasColumnType("int")
                        .HasColumnName("song_id");

                    b.Property<DateTime?>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId", "SongId")
                        .HasName("pk_user_song_favorite");

                    b.HasIndex("SongId");

                    b.ToTable("UserSongFavorites");
                });

            modelBuilder.Entity("FinalAppTemplate.Models.Recommendation", b =>
                {
                    b.HasOne("FinalAppTemplate.Models.Song", "Song")
                        .WithMany("Recommendations")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Recommend__song___4AB81AF0");

                    b.HasOne("FinalAppTemplate.Models.User", "User")
                        .WithMany("Recommendations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Recommend__user___49C3F6B7");

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinalAppTemplate.Models.Session", b =>
                {
                    b.HasOne("FinalAppTemplate.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Sessions__user_i__3E52440B");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinalAppTemplate.Models.UserSongFavorite", b =>
                {
                    b.HasOne("FinalAppTemplate.Models.Song", "Song")
                        .WithMany("UserSongFavorites")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserSongF__song___45F365D3");

                    b.HasOne("FinalAppTemplate.Models.User", "User")
                        .WithMany("UserSongFavorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserSongF__user___44FF419A");

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinalAppTemplate.Models.Song", b =>
                {
                    b.Navigation("Recommendations");

                    b.Navigation("UserSongFavorites");
                });

            modelBuilder.Entity("FinalAppTemplate.Models.User", b =>
                {
                    b.Navigation("Recommendations");

                    b.Navigation("Sessions");

                    b.Navigation("UserSongFavorites");
                });
#pragma warning restore 612, 618
        }
    }
}
